---
name: Linters

on:
  push:
    branches:
      - 'dev'
      - 'main'

  pull_request:
    branches:
      - 'dev'
      - 'main'

jobs:
  "Black":
    runs-on: ubuntu-latest
    container: python:3.10

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: pip install black

      - name: Run black check
        run: black --check .
